config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root   "static_pages#home"
  get    "/signup",      to: "authors#new"
  get    "/settings",    to: "authors#edit"
  get    "/showarticle", to: "articles#show"
  get    "/login",       to: "sessions#new"
  post   "/login",       to: "sessions#create"
  delete "/logout",      to: "sessions#destroy"
  resources :authors
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  default_scope -> { order(created_at: :desc) }
  validates :author_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_one :image
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  def Author.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.min_cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = current_author.articles.build(article_params)
    if @article.save
      flash[:success] = "Article created!"
      redirect_to root_url
    else
      @feed_item = current_author.feed.paginate(page: params[:page])
      render "static_pages/home", status: :unprocessable_entity
    end
  end

  def show
    @article = Article.find(params[:id])
    @author = Author.find(@article.author_id)
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :content)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def edit
  end

  def show
    @author = Author.find(params[:id])
    @articles = @author.articles.paginate(page: params[:page], per_page: 10)
    @custom_renderer = CustomLinkRenderer.new
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      reset_session
      log_in @author
      flash[:success] = "ユーザー登録しました。"
      redirect_to root_url
    else
      render "new", status: :unprocessable_entity
    end
  end

  private
    def author_params
      params.require(:author).permit(:name, :email, :password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    author = Author.find_by(email: params[:session][:email].downcase)
    if author && author.authenticate(params[:session][:password])
      reset_session
      log_in author
      redirect_to author
    else
      flash.now[:danger] = "Invalid email/password"
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @author = current_author
    if @author
      @your_articles = @author.articles.paginate(page: params[:page], per_page: 10)
    end
    @articles = Article.all.paginate(page: params[:page], per_page: 10)
    @custom_renderer = CustomLinkRenderer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_created_at(record)
    record.created_at.strftime('%B %e').sub(/(?<=\d)(?=(\d{2})+(\D|$))/, '\&<span class="date">th</span>').html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(author)
    session[:author_id] = author.id
  end

  def current_author
    if session[:author_id]
      @current_author ||= Author.find_by(id: session[:author_id])
    end
  end

  def current_author?(author)
    author && author == current_author
  end

  def logged_in?
    !current_author.nil?
  end

  def log_out
    reset_session
    @current_author = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

class CustomLinkRenderer < WillPaginate::ActionView::LinkRenderer
  def container_attributes
    super.except(:first_label, :last_label, :next_label, :previous_label)
  end

  def page_number(page)
    if page == current_page
      tag(:li, tag(:a, page, class: 'page-link'), class: 'page-item active')
    else
      tag(:li, link(page, page, rel: rel_value(page), class: 'page-link'), class: 'page-item')
    end
  end

  def previous_or_next_page(page, text, classname)
    if page
      tag(:li, link(text, page, class: 'page-link'), class: "page-item #{classname}")
    else
      tag(:li, tag(:span, text, class: 'page-link'), class: "page-item #{classname} disabled")
    end
  end

  def gap
    tag(:li, tag(:span, '...'), class: 'page-item disabled gap display-none')
  end
end

app/views/articles/_article.html.erb
<div id="article-<%= article.id %>" class="article-preview">
  <div class="article-meta">
    <%= link_to image_tag("demo-avatar.png", alt: "man icon"), article.author %>
    <div class="info">
      <%= link_to article.author.name, article.author, class: "author" %>
      <span class="date"><%= formatted_created_at(article) %></span>
    </div>
    <button class="btn btn-outline-primary btn-sm pull-xs-right">
      <i class="ion-heart"></i> 29
    </button>
  </div>
  <%= link_to article, class: "preview-link" do %>
    <h1><%= article.title %></h1>
    <p><%= article.description %></p>
    <span>Read more...</span>
    <ul class="tag-list">
      <li class="tag-default tag-pill tag-outline">realworld</li>
      <li class="tag-default tag-pill tag-outline">implementations</li>
    </ul>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">

        <%= form_with(model: @article) do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>

          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control form-control-lg", placeholder: "What's this article about?" %>

          <%= f.label :content %>
          <%= f.text_area :content, rows: "10", class: "form-control form-control-lg", placeholder: "Write your article (in markdown)" %>

          <%= f.submit "Publish Article", class: "btn btn-lg pull-xs-right btn-primary mt-2"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>

      <div class="article-meta">
        <%= link_to image_tag("demo-avatar.png"), @author %>
        <div class="info">
          <%= link_to @author.name, @author, class: "white" %>
          <span class="date">January 20th</span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; <%= @author.name %> <span class="counter">(10)</span>
        </button>
        &nbsp;&nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Post <span class="counter">(29)</span>
        </button>
        <% if current_author?(@author) %>
          <button class="btn btn-sm btn-outline-secondary">
            <i class="ion-edit"></i> Edit Article
          </button>
          <button class="btn btn-sm btn-outline-danger">
            <i class="ion-trash-a"></i> Delete Article
          </button>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p>
          <%= @article.description %>
        </p>
        <div>
          <%= @article.content.html_safe %>
        </div>
        <ul class="tag-list">
          <li class="tag-default tag-pill tag-outline">realworld</li>
          <li class="tag-default tag-pill tag-outline">implementations</li>
        </ul>
      </div>
    </div>

    <hr />

    <div class="article-actions">
      <div class="article-meta">
        <%= link_to image_tag("demo-avatar.png"), @author %>
        <div class="info">
          <%= link_to @author.name, @author, class: "author" %>
          <span class="date">January 20th</span>
        </div>

        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow <%= @author.name %>
        </button>
        &nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Article <span class="counter">(29)</span>
        </button>
        <% if current_author?(@author) %>
          <button class="btn btn-sm btn-outline-secondary">
            <i class="ion-edit"></i> Edit Article
          </button>
          <button class="btn btn-sm btn-outline-danger">
            <i class="ion-trash-a"></i> Delete Article
          </button>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <form class="card comment-form">
          <div class="card-block">
            <textarea class="form-control" placeholder="Write a comment..." rows="3"></textarea>
          </div>
          <div class="card-footer">
            <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            <button class="btn btn-sm btn-primary">Post Comment</button>
          </div>
        </form>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
            <span class="mod-options">
              <i class="ion-trash-a"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/edit.html.erb
<div class="settings-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Your Settings</h1>

        <ul class="error-messages">
          <li>That name is required</li>
        </ul>

        <form>
          <fieldset>
            <fieldset class="form-group">
              <input class="form-control" type="text" placeholder="URL of profile picture" />
            </fieldset>
            <fieldset class="form-group">
              <input class="form-control form-control-lg" type="text" placeholder="Your Name" />
            </fieldset>
            <fieldset class="form-group">
              <textarea
                class="form-control form-control-lg"
                rows="8"
                placeholder="Short bio about you"
              ></textarea>
            </fieldset>
            <fieldset class="form-group">
              <input class="form-control form-control-lg" type="text" placeholder="Email" />
            </fieldset>
            <fieldset class="form-group">
              <input
                class="form-control form-control-lg"
                type="password"
                placeholder="New Password"
              />
            </fieldset>
            <button class="btn btn-lg btn-primary pull-xs-right">Update Settings</button>
          </fieldset>
        </form>
        <hr />
        <button class="btn btn-outline-danger">Or click here to logout.</button>
      </div>
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<div class="auth-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Sign up</h1>
        <p class="text-xs-center">
          <%= link_to "Have an account?", "#" %>
        </p>

        <%= form_with(model: @author) do |f| %>
          <%= render "shared/error_messages" %>

          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control form-control-lg", placeholder: "Username"%>

          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control form-control-lg", placeholder: "Email"%>

          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control form-control-lg", placeholder: "Password"%>

          <%= f.submit "Sign up", class: "btn btn-lg btn-primary pull-xs-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<div class="profile-page">
  <div class="user-info">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-10 offset-md-1">
          <%= image_tag "demo-avatar.png", class: "user-img" %>
          <h4><%= @author.name %></h4>
          <p>
            Cofounder @GoThinkster, lived in Aol's HQ for a few months, kinda looks like Peeta from
            the Hunger Games
          </p>
          <button class="btn btn-sm btn-outline-secondary action-btn">
            <i class="ion-plus-round"></i>
            &nbsp; Follow <%= @author.name %>
          </button>
          <button class="btn btn-sm btn-outline-secondary action-btn">
            <i class="ion-gear-a"></i>
            &nbsp; Edit Profile Settings
          </button>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1">
        <div class="articles-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link active" href="">My Articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Favorited Articles</a>
            </li>
          </ul>
        </div>

        <% if @author.articles.any? %>
          <%= render @articles %>
          <%= will_paginate @articles, renderer: @custom_renderer %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <%= link_to "conduit", "#" %>
    <span class="attribution">
      An interactive learning project from <%= link_to "Thinkster", "https://thinkster.io" %>. Code &amp;
      design licensed under MIT.
    </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light">
  <div class="container">
    <%= link_to "conduit", root_path, class: "navbar-brand"%>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <!-- Add "active" class when you're on that page" -->
        <%= link_to "Home", root_path, class: "nav-link active" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to new_article_path, class: "nav-link" do %>
            <i class="ion-compose"></i>&nbsp;New Article
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to settings_path, class: "nav-link" do %>
            <i class="ion-gear-a"></i>&nbsp;Settings
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", logout_path, class: "nav-link", data: { "turbo-method": :delete } %>
        </li>
        <li class="nav-item">
          <%= link_to current_author, class: "nav-link" do %>
            <%= image_tag "demo-avatar.png", class: "user-pic" %>
            <%= current_author.name %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conduit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <link
    href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    rel="stylesheet"
    type="text/css"
    />
    <link
      href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link rel="stylesheet" href="//demo.productionready.io/main.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container" >
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @author.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@author.errors.count, "error") %>.
    </div>
    <ul>
    <% @author.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_aricle_perview.html.erb
<div id="article-<%= article.id %>" class="article-preview">
  <div class="article-meta">
    <%= link_to image_tag("demo-avatar.png", alt: "man icon"), article_path(:id) %>
    <div class="info">
      <%= link_to article.author.name, article.author, class: "author" %>
      <span class="date">January 20th</span>
    </div>
    <button class="btn btn-outline-primary btn-sm pull-xs-right">
      <i class="ion-heart"></i> 29
    </button>
  </div>
  <%= link_to article, class: "preview-link" do %>
    <h1><%= article.title %></h1>
    <p><%= article.description %></p>
    <span>Read more...</span>
    <ul class="tag-list">
      <li class="tag-default tag-pill tag-outline">realworld</li>
      <li class="tag-default tag-pill tag-outline">implementations</li>
    </ul>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Your Feed", "#", class: "nav-link" %>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Global Feed", "#", class: "nav-link active" %>
            </li>
          </ul>
        </div>

        <%= render @articles %>
        <%= will_paginate @articles, renderer: @custom_renderer %>

      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>